### ISSUE TITLE
problems with installing

### ISSUE THREAD

**Issue by seif3r** [phase2/particle#223]
i'm having difficulties installing with both yarn and npm. Installing it on a drupal 8 site on a ubuntu 16 virtualbox.

i'm using:
Node: v9.4.0
npm: 5.6.0
yarn: 1.3.2

while doing the yarn install i get the following error message to abort the process:

> 
> rm -f Release/obj.target/src/sass.a && ar crs Release/obj.target/src/sass.a Release/obj.target/libsass/src/libsass/src/ast.o Release/obj.target/libsass/src/libsass/src/base64vlq.o Release/obj.target/libsass/src/libsass/src/bind.o Release/obj.target/libsass/src/libsass/src/cencode.o Release/obj.target/libsass/src/libsass/src/color_maps.o Release/obj.target/libsass/src/libsass/src/constants.o Release/obj.target/libsass/src/libsass/src/context.o Release/obj.target/libsass/src/libsass/src/cssize.o Release/obj.target/libsass/src/libsass/src/emitter.o Release/obj.target/libsass/src/libsass/src/environment.o Release/obj.target/libsass/src/libsass/src/error_handling.o Release/obj.target/libsass/src/libsass/src/eval.o Release/obj.target/libsass/src/libsass/src/expand.o Release/obj.target/libsass/src/libsass/src/extend.o Release/obj.target/libsass/src/libsass/src/file.o Release/obj.target/libsass/src/libsass/src/functions.o Release/obj.target/libsass/src/libsass/src/inspect.o Release/obj.target/libsass/src/libsass/src/json.o Release/obj.target/libsass/src/libsass/src/lexer.o Release/obj.target/libsass/src/libsass/src/listize.o Release/obj.target/libsass/src/libsass/src/memory_manager.o Release/obj.target/libsass/src/libsass/src/node.o Release/obj.target/libsass/src/libsass/src/output.o Release/obj.target/libsass/src/libsass/src/parser.o Release/obj.target/libsass/src/libsass/src/plugins.o Release/obj.target/libsass/src/libsass/src/position.o Release/obj.target/libsass/src/libsass/src/prelexer.o Release/obj.target/libsass/src/libsass/src/remove_placeholders.o Release/obj.target/libsass/src/libsass/src/sass.o Release/obj.target/libsass/src/libsass/src/sass2scss.o Release/obj.target/libsass/src/libsass/src/sass_context.o Release/obj.target/libsass/src/libsass/src/sass_functions.o Release/obj.target/libsass/src/libsass/src/sass_util.o Release/obj.target/libsass/src/libsass/src/sass_values.o Release/obj.target/libsass/src/libsass/src/source_map.o Release/obj.target/libsass/src/libsass/src/to_c.o Release/obj.target/libsass/src/libsass/src/to_value.o Release/obj.target/libsass/src/libsass/src/units.o Release/obj.target/libsass/src/libsass/src/utf8_string.o Release/obj.target/libsass/src/libsass/src/util.o Release/obj.target/libsass/src/libsass/src/values.o
>   rm -rf "Release/sass.a" && cp -af "Release/obj.target/src/sass.a" "Release/sass.a"
> cp: preserving permissions for ‘Release/sass.a’: Operation not permitted
> src/libsass.target.mk:191: recipe for target 'Release/sass.a' failed
> make: Leaving directory '/var/www/drupal8-2/web/themes/custom/patternlab/node_modules/node-sass/build'
> make: *** [Release/sass.a] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/var/www/drupal8-2/web/themes/custom/patternlab/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
> gyp ERR! System Linux 4.4.0-87-generic
> gyp ERR! command "/home/vagrant/.nvm/versions/node/v9.4.0/bin/node" "/var/www/drupal8-2/web/themes/custom/patternlab/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd /var/www/drupal8-2/web/themes/custom/patternlab/node_modules/node-sass
> gyp ERR! node -v v9.4.0

**Comment by geoff-winner** [comment]
Hey there,

I'll start by asking if you have tried rebuilding node-sass with npm? Just curious, might give us an immediate idea of what is going on..

I found this thread possibly discussing a similar issue that could be helpful as well, https://github.com/sass/node-sass/issues/1918

**Comment by anniegreens** [comment]
@seif3r Also, we've verified successful install with the last two LTS node versions not with v9+. If you haven't tried using node v8 you may want to give that a shot.

**Comment by seif3r** [comment]
I tried with rebuilding node-sass and with node v8.9.4 but that didn't work.

I did get it to work eventually with the following:
node v6.9.1 / npm 3.10.8

**Comment by illepic** [comment]
@seif3r : This works in OSX and Ubuntu 16.04 for me with Node 8/NPM 5. 

It looks like you're having permissions issues when attempting to compile Sass up above. Have you looked into that?

**Comment by illepic** [comment]
Closing due to inactivity.
