### ISSUE TITLE
Can't run Drupal development-mode "npm run dev:drupal"

### ISSUE THREAD

**Issue by chkilel** [phase2/particle#321]
Executing "npm run dev:drupal" lead to an error, bellow is the errorlog, I tried using node 8.11.3 and node 8.0.0 but the same error occurred
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/adil/.nvm/versions/node/v8.11.3/bin/node',
1 verbose cli   '/home/adil/.nvm/versions/node/v8.11.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev:drupal' ]
2 info using npm@6.1.0
3 info using node@v8.11.3
4 verbose run-script [ 'predev:drupal', 'dev:drupal', 'postdev:drupal' ]
5 info lifecycle Particle@10.0.0~predev:drupal: Particle@10.0.0
6 info lifecycle Particle@10.0.0~dev:drupal: Particle@10.0.0
7 verbose lifecycle Particle@10.0.0~dev:drupal: unsafe-perm in lifecycle true
8 verbose lifecycle Particle@10.0.0~dev:drupal: PATH: /home/adil/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/Adil/Sites/drupal/gsmalki/web/themes/particle/node_modules/.bin:/home/adil/.nvm/versions/node/v8.11.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/cmder/vendor/conemu-maximus5:/mnt/c/cmder/vendor/conemu-maximus5/ConEmu:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Windows/System32:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/mnt/c/Program Files/dotnet:/mnt/c/Program Files (x86)/Common Files/Alpi Shared:/mnt/c/Program Files (x86)/Common Files/Alpi Shared:/mnt/c/Program Files/Calibre2:/mnt/c/E20-II/ENVIRO:/mnt/c/Program Files (x86)/Brackets/command:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Users/Adil/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files/Git/bin:/mnt/c/Program Files/Lando:/mnt/c/Users/Adil/AppData/Local/hyper/app-2.0.0/resources/bin:/mnt/c/Program Files/Lando/bin:/mnt/c/Users/Adil/AppData/Local/Keybase
9 verbose lifecycle Particle@10.0.0~dev:drupal: CWD: /mnt/c/Users/Adil/Sites/drupal/gsmalki/web/themes/particle
10 silly lifecycle Particle@10.0.0~dev:drupal: Args: [ '-c',
10 silly lifecycle   'npm-run-all --continue-on-error --parallel dev:drupal:gulp dev:drupal:webpack' ]
11 silly lifecycle Particle@10.0.0~dev:drupal: Returned: code: 1  signal: null
12 info lifecycle Particle@10.0.0~dev:drupal: Failed to exec dev:drupal script
13 verbose stack Error: Particle@10.0.0 dev:drupal: `npm-run-all --continue-on-error --parallel dev:drupal:gulp dev:drupal:webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/adil/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/adil/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid Particle@10.0.0
15 verbose cwd /mnt/c/Users/Adil/Sites/drupal/gsmalki/web/themes/particle
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/home/adil/.nvm/versions/node/v8.11.3/bin/node" "/home/adil/.nvm/versions/node/v8.11.3/bin/npm" "run" "dev:drupal"
18 verbose node v8.11.3
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error Particle@10.0.0 dev:drupal: `npm-run-all --continue-on-error --parallel dev:drupal:gulp dev:drupal:webpack`
22 error Exit status 1
23 error Failed at the Particle@10.0.0 dev:drupal script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by illepic** [comment]
We have an update going into this tonight!

**Comment by illepic** [comment]
This is updated in master now via https://github.com/phase2/particle/pull/322
