### ISSUE TITLE
npm start lead to an error

### ISSUE THREAD

**Issue by chkilel** [phase2/particle#324]
npm star doesn't compile PL and lead to an Error: Cannot find module 'eslint-config-airbnb'

```
particle|⇒ npm start

> particle@10.0.0 start /mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle
> npm run dev:pl


> particle@10.0.0 dev:pl /mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle
> NODE_ENV='development' webpack-dev-server --config ./apps/pl/webpack.pl.dev.js --hot

🚀 Pattern Lab development build running! 🚀
[20:05:52] Using gulpfile /mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/gulpfile.js
[20:05:52] Starting 'compile:startup'...
[20:05:52] Starting 'compile:pl:env'...
[20:05:52] Finished 'compile:pl:env' after 11 ms
[20:05:52] Starting 'compile'...
[20:05:52] Starting 'compile:twig-namespaces'...
[20:05:53] Finished 'compile:twig-namespaces' after 824 ms
[20:05:53] Starting 'compile:pl'...
configuring pattern lab...
your site has been generated...
site generation took 13.50614118576 seconds and used 18MB of memory...
42...

[20:06:07] Finished 'compile:pl' after 14 s
[20:06:07] Starting 'compile:pl:notify'...
[20:06:07] Finished 'compile:pl:notify' after 8.67 ms
[20:06:07] Finished 'compile' after 15 s
[20:06:07] Finished 'compile:startup' after 15 s
(node:2985) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ℹ ｢wds｣: Project is running at http://localhost:8086/
ℹ ｢wds｣: webpack output is served from /assets/
ℹ ｢wds｣: Content not from webpack is served from /mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/dist
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: wait until bundle finished: /assets/astrogoat.png
ℹ ｢wdm｣: wait until bundle finished: /assets/app-pl.js?cacheBuster=85068643
✖ ｢wdm｣: Hash: b716d66e3df13e5f2160
Version: webpack 4.12.0
Time: 16539ms
Built at: 2018-06-22 19:06:24
PublicPath: /assets/
    Asset     Size  Chunks             Chunk Names
app-pl.js  368 KiB  app-pl  [emitted]  app-pl
Entrypoint app-pl = app-pl.js

ERROR in ./apps/pl/index.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'eslint-config-airbnb'
Referenced from: /mnt/c/Users/Adil/Sites/drupal/gsm/web/core/.eslintrc.json
Referenced from: /mnt/c/Users/Adil/Sites/drupal/gsm/web/.eslintrc.json
    at ModuleResolver.resolve (/mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/node_modules/eslint/lib/config/config-file.js:479:28)
    at load (/mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/node_modules/eslint/lib/config/config-file.js:551:26)
    at configExtends.reduceRight (/mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/node_modules/eslint/lib/config/config-file.js:425:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/node_modules/eslint/lib/config/config-file.js:403:26)
    at loadFromDisk (/mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/node_modules/eslint/lib/config/config-file.js:523:22)
    at load (/mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/node_modules/eslint/lib/config/config-file.js:559:20)
    at configExtends.reduceRight (/mnt/c/Users/Adil/Sites/drupal/gsm/web/themes/particle/node_modules/eslint/lib/config/config-file.js:425:36)
    at Array.reduceRight (<anonymous>)
 @ multi (webpack)-dev-server/client?http://localhost:8086 webpack/hot/dev-server ./apps/pl/index.js
ℹ ｢wdm｣: Failed to compile.

**Comment by chkilel** [comment]
Thank you illeptic
I'm on node 8.11.3 and npm 6.1.0, I did what you mentionend above but the same problem apeare, I'm using the master branche of particle, I tried with the beta 3, it work but has a problem with the drupal dev compilation.
I switched to master branche because of the #322

**Comment by illepic** [comment]
Ah. I see. eslint is trying to read your root drupal `.eslintrc.json` file ...

**Comment by illepic** [comment]
Note the explanation of `root: true` here: https://eslint.org/docs/user-guide/configuring.

Edit the root Particle .`eslintrc.js` to include `root: true,`.

**Comment by illepic** [comment]
Pull request here to bake this in by default: https://github.com/phase2/particle/pull/330

**Comment by chkilel** [comment]
Thank you illeptic, the problem is solved.
