### ISSUE TITLE
Unable to create a new component when I have a folder name with spaces or parentheses

### ISSUE THREAD

**Issue by truls1502** [phase2/particle#583]
I am mac users and using Dropbox business account to store my works. I would like to work directly on Dropbox instead of on local then move the folder thereafter. 

The challenge is that the folder name of Dropbox is such as `Dropbox (Company name)`. When I am trying to create a 

I am using Particle: 10.2.1

```
Truls-MBP:~ truls1502$ ln -s '/Users/truls1502/Dropbox (SignWo AS)/git' git           
Truls-MBP:~ truls1502$ cd git/projects/websitename/web/themes/custom/particle
Truls-MBP:particle truls1502$ pwd
/Users/truls1502/git/projects/websitename/web/themes/custom/particle

Truls-MBP:particle truls1502$ npm run new

> particle@10.2.1 new /Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle
> yo ./tools/new-component/index.js

Hi! This will help you build a component folder with assets.
      Templates for this are in: tools/new-component
? To which design system would you like to add this new component? default
? Where would you like this new component? 03-organisms
? Where in here? ./
? What shall we name it? testtruls
events.js:174
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/tools/new-component/templates/_pattern.scss
    at EditionInterface.exports.copy (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at generatorAssets.(anonymous function).forEach.file (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/tools/new-component/index.js:132:17)
    at Array.forEach (<anonymous>)
    at Object.keys.map.fileType (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/tools/new-component/index.js:131:33)
    at Array.map (<anonymous>)
    at module.exports.writing (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/tools/new-component/index.js:130:34)
    at Object.<anonymous> (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! particle@10.2.1 new: `yo ./tools/new-component/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the particle@10.2.1 new script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/truls1502/.npm/_logs/2019-07-30T11_07_10_428Z-debug.log
```

Is there some workaround?

**Comment by jryanconklin** [comment]
@truls1502 Howdy! Looking into this I'm not sure that Particle can make a fix for this. Our `new` step is built on Yeoman. I'm guessing this more accurately an issue with that project:

https://yeoman.io/contributing/

Thank you so much! I'm going to close this issue as I'm not sure there's anything we can do here.

**Comment by truls1502** [comment]
You are right that it is not a Particle problem. But it doesn't only happen when running on `npm run new'`. 

Sometimes on build too like I am getting warnings such as: `syntax error near unexpected token '('`

I appreciate a lot if you could help us to troubleshoot or point precisely where it is making such problems. So we both or I could report it to the package(s) provider you are using to ask nicely if they could fix the issue? The more people are asking, the more chance they are willing to fix it. In case if it is taking a long time, maybe we could create a patch on the package(s). I am open to other ideas or solution. 

So what happens to you if you are creating a folder like `Particle (Company)` then git clone Particle, and run `git checkout` on the `tags/10.2.1` inside in the folder. After that, run different scripts-commands from the script-list. 

Is it only yeoman that cause the problem which we could report it to or several of the packages you are using?

I hope for positive answer and able to get your help too! 😊
